on:
  workflow_dispatch:
jobs:
  build:
    name: Update site
    runs-on: ubuntu-latest
    steps:
      - name: Clone La Cipollina Budgeter
        run: git clone https://github.com/ehanahamed/la-cipollina-budgeter.git
      - name: Clone freehold.dev
        run: git clone https://github.com/ehanahamed/freehold.dev.git
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: npm run build
        run: |
          cd la-cipollina-budgeter/web
          npm install
          npm run build
      - name: Copy web/build/ into freehold.dev/site/la-cipollina-budgeter/
        run: |
          rm -rf freehold.dev/site/la-cipollina-budgeter
          cp -R la-cipollina-budgeter/web/build freehold.dev/site/la-cipollina-budgeter
      - name: Commit & push to freehold.dev
        run: |
          cd site
          git add .
          git config --global user.name "Ehan"
          git config --global user.email "ehanahamed@ehan.dev"
          git commit -m "Update La Cipollina Budgeter"
          git push https://ehanahamed:${{ secrets.GH_TOKEN }}@github.com/ehanahamed/freehold.dev.git --all
